### ISSUE TITLE
'st-256color': unknown terminal type.

### ISSUE THREAD

**Issue by GasparVardanyan** [LukeSmithxyz/st#106]
┌─[gaspar@GasparVardanyan]─[~]
└──╼ $ clear
'st-256color': unknown terminal type.
┌─[✗]─[gaspar@GasparVardanyan]─[~]
└──╼ $ cat .Xresources.d/st
st.foreground:                Red
st.background:                Black
st.cursorColor:               #d40000
st.alpha:                     .85

**Comment by GasparVardanyan** [comment]
Also Backspace doesn't work, instead of deleting a character, backspace applies space in the inputed text.
But after TERM=xterm command all works fine (clear command, backspace).

**Comment by ZethJack** [comment]
I've been having similar issue with tmux - trying to start a session resulted in getting "server exitted unexpectedly" error.
Apparently the issue is related to Arch lacking correct terminfo entry for "st-256color" to which ST defaults to in it's config pre-compilation.
Running `tic -sx st.info` inside st's source directory will generate the necessary `.terminfo` entries in your `$HOME` dir.
That fixed the issue for me, sadly I have no idea how to do such a thing for installations from AUR
