### ISSUE TITLE
Blinking clock in ncmpcpp

### ISSUE THREAD

**Issue by Mati20187** [LukeSmithxyz/st#107]
The clock in ncmpcpp is blinking. This problem only occurs in st (urxvt and xfce terminal work fine in this regard). I've tried changing xfps and actionfps to in config.h to different values with no luck. Is there any way to fix it? 
Thanks in advance!
https://youtu.be/qeqgBJYxPwM

**Comment by antenore** [comment]
I confirm this as well. I've tried to bisect the original st till the 0.4 version, but the problem was always there, than I've found this fork (amazing job @LukeSmithxyz !!! ) and thought that maybe it's worth following up this issue here. 
 
What I see is that each flickering happens at each iteration of the main redraw loop.
Redrawing shouldn't happen if there's no real changes to draw, but I don't know how to debug further this as I don't know enough well both libs (xcb/xlib and ncurses). 
Either ncurses send a signal that is interpreted as a window change, either st does the redraw when it shouldn't. 

If anybody would be so nice to guide me on the right track...

**Comment by DannyMexen** [comment]
> I confirm this as well. I've tried to bisect the original st till the 0.4 version, but the problem was always there, than I've found this fork (amazing job @LukeSmithxyz !!! ) and thought that maybe it's worth following up this issue here.
> 
> What I see is that each flickering happens at each iteration of the main redraw loop.
> Redrawing shouldn't happen if there's no real changes to draw, but I don't know how to debug further this as I don't know enough well both libs (xcb/xlib and ncurses).
> Either ncurses send a signal that is interpreted as a window change, either st does the redraw when it shouldn't.
> 
> If anybody would be so nice to guide me on the right track...

So, your solution was Luke's fork?

**Comment by Mati20187** [comment]
@DannyMexen you can get rid of the blinking/rendering issues by applying the _sync_ patch: https://st.suckless.org/patches/sync/
