### ISSUE TITLE
Delete key does not work

### ISSUE THREAD

**Issue by anselal** [LukeSmithxyz/st#11]
Is the delete key supposed to do nothing at all ? Am I missing something here ?

**Comment by LukeSmithxyz** [comment]
The delete key is not mapped. If you want it, look to [this patch](https://st.suckless.org/patches/delkey/). You'll have to manually mimic it in adding it though since this build is 8.0+. If I get the chance I might patch it into my build, although since I use vi mode in the shell, it's not so useful.
