### ISSUE TITLE
Change the default cursor

### ISSUE THREAD

**Issue by fsmiamoto** [LukeSmithxyz/st#122]
I've tried to change the default cursor shape by editing the `config.h` file as
follows:
```c
/*
 * Default shape of cursor
 * 2: Block ("█")
 * 4: Underline ("_")
 * 6: Bar ("|")
 * 7: Snowman ("☃")
 */
static unsigned int cursorshape = 6;
```
Then, I've ran `make && sudo make install` but seems like the cursor didn't change as expected.

Is there something I should watch out for?

- Shell: zsh

**Comment by decantr** [comment]
Probably your shell overwriting it. What does your `.zshrc` look like?

**Comment by azzamsa** [comment]
It worked for me https://github.com/LukeSmithxyz/st/issues/121, because I don't do `make install`, but:

```
$ make
$ ln -s /opt/stterm/st  /usr/local/bin/st
```

So any new changes always point to my newest binary.

Maybe you need to check:

1. run ./st inside your newest compilation, if this work that means all the `make install` process links still point to the old binary.
2. run st without any of your "additional" bash config. as @decantr suggested

**Comment by fsmiamoto** [comment]
@decantr @azzamsa 
It really seems like the shell is overwriting it.

After running `make install`, I've tried
```bash
# Does not read .zshrc
$ st -e zsh -f
```
Now the cursor has changed appropriately.

Thanks for the suggestions!
Now I know where to look into for the solution
