### ISSUE TITLE
alt + c "COPY" selected not working

### ISSUE THREAD

**Issue by codeitlikemiley** [LukeSmithxyz/st#140]
Hi ive just notice lately that ALT + c in st doesnt copy the selected characters
im using zsh
in vi visual mode when i select characters and alc it wont copy it.
but selecting with mouse left click and drag the selected text is copy automatic without pressing alt +c

i can live without alt + c but can u pint point what line and file i should edit on this repo to modify it?

**Comment by LukeSmithxyz** [comment]
Well yeah, it's not supposed to work: `y` copies in vim of course. Visual selection in vim and highlighting with a terminal are technically distinct.

I'm guessing you have `set mouse=a` so that mouse selection overrides visual mode, but for people who don't have that, you could visually select some text in vim then highlight other text at the same time with the mouse.

So long as you have a line like `set clipboard+=unnamedplus` in you gvim or neovim config, `y` will copy to the clipboard anyway.
