### ISSUE TITLE
Colors from escape sequences and pywal are weird.

### ISSUE THREAD

**Issue by huBIerTi2** [LukeSmithxyz/st#142]
Here is `st` just after spawning:
![o1](https://user-images.githubusercontent.com/16193899/69711757-e605ca00-1101-11ea-9970-8c376abdcb1c.jpg)
It's okay accounting for the alpha value 0.8.

The problems appear after any refresh of `wal`, no matter if it's a reload of `i3` or `wal -R`. The background color doesn't correspond to any of the colors shown by the preview of pywal:
![o2](https://user-images.githubusercontent.com/16193899/69712076-80fea400-1102-11ea-8fd3-272ab1372e17.jpg)

Here's also my only entries in _.Xresources_:
```
*.font:	Fantasque Sans Mono:pixelsize=20;
*.alpha: 0.8
```

I noticed that this also happens whenever I do `(cat ~/.cache/wal/sequences &)`, which means that it probably has something to do with escape sequences. Is there any way to fix it?

Thanks in advance,
Hubert.

**Comment by aleksfadini** [comment]
Same problem here.

**Comment by terriblephrases** [comment]
Pywal sets colorindex 256 to your foreground color: https://github.com/dylanaraps/pywal/blob/master/pywal/sequences.py#L58

Luke's st uses colorindex 256 for the background: https://github.com/LukeSmithxyz/st/blob/master/config.h#L109

Upstream st uses colorindex 256 for the cursor: https://git.suckless.org/st/file/config.def.h.html#l110

Fixing this would require either going back to st defaults and/or adding the OSC escape sequences Pywal uses in addition to `]4;colorindex;colorname` (setcolor): https://github.com/dylanaraps/pywal/blob/master/pywal/sequences.py#L46

**Comment by bradwood** [comment]
I'm also having the same problem. The escape code hack doesn't seem to work either when I run it in an `st` instance... 

I think is completely breaking `pywal` integration which is a shame...

Is there not some less hacky way of fixing this?

**Comment by terriblephrases** [comment]
I forgot to add the -e option to echo: `echo -e "\e]4;256;#123456\a"` and I already said what the less hacky way of fixing it is.

**Comment by aleksfadini** [comment]
I couldn't fix it, reverted back to urxvt instead of st...

**Comment by Jemi** [comment]
Instead of escape sequence hacks,  the best solution is another patch to st (or fix the xresources patch or use an alternate) so that st reloads it's xresources upon receiving a certain process signal (possibly signal 10 or 12), and then change pywal to send this signal instead of escape codes. This would not only fix the pywal issue, but more generally allow st to reload its resources, and _should_ even allow changing alpha on the fly, which would be _extremely_ useful.

**Comment by Jemi** [comment]
So, after doing some research, it turns out that approximately zero programs dynamically reload their Xresources. So it looks like escape codes _are_ going to be the way ST gets dynamically themed. I've written a shell script workaround: http://dpaste.com/1BT8TE7 which can be deployed something like "wal -o <your_path>/wal_sequences_helper.sh --theme base16-black-metal-bathory"

This workaround is NOT sufficient by itself. The inconsistent palette needs to be fixed in config.h. Under: 
/*
 * Default colors (colorname index)
 * foreground, background, cursor, reverse cursor
 */

Try this:
unsigned int defaultfg = 259;
unsigned int defaultbg = 258;
static unsigned int defaultcs = 256;
static unsigned int defaultrcs = 257;

and at the end of   static const char *colorname[] = {, try this:
	/* more colors can be added after 255 to use with DefaultXX */
	"#add8e6", /* 256 -> cursor */
	"#555555", /* 257 -> rev cursor*/
	"#282828",   /* 258 -> bg */
	"#ebdbb2",   /* 259 -> fg */

And if you want new instances to get the updated background, then you will need to fix ResourcePref resources[]:

{ "background",   STRING,  &colorname[258] },
{ "foreground",   STRING,  &colorname[259] },
{ "cursorColor",  STRING,  &colorname[256] },

The alpha patch and the xresources patch don't agree on what goes under what palette. I suspect that what I've suggested here, or something similar, will be agreeable to everyone. You should talk to the various ST developers involved and see if they can standardize on something while we're waiting for proper OSC sequence support, which may not come for awhile.  Then talk to the pywal developer and ask him if he could simply implement the appropriate palette codes. There are more that I didn't convert in the script, which you can see using this unmap tool: https://invisible-island.net/misc_tools/index.html#item:unmap and you can check this reference to see what they mean: http://pod.tst.eu/http://cvs.schmorp.de/rxvt-unicode/doc/rxvt.7.pod#XTerm_Operating_System_Commands.

**Comment by Spryc** [comment]
Having the same issue, could you link the script? It has disappeared

**Comment by Jemi** [comment]
This should work: https://gist.github.com/Jemi/e4e0be91faeb647c94e2bc957d9246e8
