### ISSUE TITLE
output disappears if resizing terminal? 

### ISSUE THREAD

**Issue by thepenguinthatwants** [LukeSmithxyz/st#146]
When I make window smaller and then back to bigger.. things disappears from the terminal.

It seems to happen everytime.

**Comment by mamg22** [comment]
This is (currently) the normal behavior of `st`, because one of its [goals](https://st.suckless.org/goals/) is not to reimplement `tmux` or other terminal multiplexers. 

While this may be annoying sometimes, this can be easily solved by using `tmux` (or similar software), which handles resizing.

**Comment by goldcoders** [comment]
noice to know you can fix this with just using tmux

**Comment by LukeSmithxyz** [comment]
I'd actually like to have this "fixed" generally without tmux because I don't think it's unreasonable for st to keep information out of its borders for when windows change size. I don't have a fix for this now because I'm not familiar with that part of the source code, but if anyone else knows, feel free to open a PR or show another build with it because I would really like this feature.

**Comment by f-person** [comment]
maybe there is a terminal multiplexer that does just that: handles text overflow? i've been looking for a terminal multiplexer like that but didn't find anything.

**Comment by LukeSmithxyz** [comment]
I'll just note that if you're using the newer versions of st, it does indeed work with suckless's scroll program. It causes some other weird effects in zsh, so I haven't switched to it yet.

**Comment by remipp** [comment]
Yes, scroll seems very buggy, especially with zsh. Would really like to use it though

**Comment by brlipi** [comment]
> I'd actually like to have this "fixed" generally without tmux because I don't think it's unreasonable for st to keep information out of its borders for when windows change size. I don't have a fix for this now because I'm not familiar with that part of the source code, but if anyone else knows, feel free to open a PR or show another build with it because I would really like this feature.

There is a build that is capable of solving this problem: https://github.com/juliusHuelsmann/st-history-vim.
On the release page (https://github.com/juliusHuelsmann/st/releases) you will find all the diff files required.

The diff file with the name of "st-columns" is the one which will fix the resizing problem. But there are a few caveats:
- It requires the "st-history" diff to function. Which I believe (I could be wrong) conflicts with the scrollback patch you can find on [st's patches page](https://st.suckless.org/patches/scrollback/).
- Since the st-history forces you to get rid of the scrollback patch, the only way to get a scrollback function to work with the other two patches (st-columns and st-history) is to get juliusHuelsmann's custom scrollback patch. Which is called "st-meta-scrollback".

From the very brief testing I've done with it, in an st (0.8.4) build with no patches but the three mentioned, the columns patch seems to work as expected, the history patch seems to function just as the history implementation of the original scrollback patch, the custom scrollback patch sometimes have the strange behavior where after scrolling up the history and then typing something, it will not scroll back down to the current shell line. This could be related to a function implemented by this custom scrollback of which I don't really know what it is supposed to do. This function also happens to share a shortcut with vanilla dwm's incnmaster function and your personal dwm build's setlayout function, so you might want to change that.

Custom scrollback historyQuit function shortcut:
```{ MODKEY,               XK_i,           historyQuit,    {.i =  0} },```
dwm's incnmaster function shortcut:
```{ MODKEY,                       XK_i,      incnmaster,     {.i = +1 } },```
Your build's setlayout function shortcut:
```{ MODKEY,			XK_i,		setlayout,	{.v = &layouts[6]} }, /* centeredmaster */```

I've looked at the [README of the repository containing the releases](https://github.com/juliusHuelsmann/st/blob/full_0.8.4/README.md) and also at [the one on the development repository](https://github.com/juliusHuelsmann/st-history-vim/blob/master/README.md) and could not find anything mentioning a "patch_column" that can work with the original scrollback patch, unfortunately.

I lack the time and know-how to tinker with these patches and try to come up with one that can work with the original scrollback patch. But for anybody willing to give it a shot, perhaps a diff file from when vim-browse was still relying on the original scrollback could give some insight or basis of comparison: https://st.suckless.org/patches/vim_browse/st-vimBrowse-20200604-295a43f.diff.

**Comment by LukeSmithxyz** [comment]
This long-standing annoyance has been solved by the upgrade to 0.8.4 alongside with the integration of `scroll` as an automatically installing gitmodule.

Enjoy.

**Comment by thepenguinthatwants** [comment]
Being using this without updating for two years :D let see what niceties it brings with it.

**Comment by gomarion** [comment]
Hey @LukeSmithxyz , have you been using the scroll tool? Are there any issues you encountered? Because I just read in their site (under "What is the state of scroll?") that it has some issues: https://tools.suckless.org/scroll/.
