### ISSUE TITLE
Text is copied after selecting it

### ISSUE THREAD

**Issue by Fogapod** [LukeSmithxyz/st#177]
### Expected behaviour
Text is copied to clipboard after selecting it and using `ALT+C` or other documented shortcut.

### Actual behaviour
Text is copied to clipboard after selecting it.
 
### Description
I'm not quite sure if it is a bug or a feature, I did not find it in the documentation.

There are shortcuts for copying text, but they seem to be completely useless because of this, they do nothing.
This behaviour is sometimes undesirable (missclicks that override clipboard).

**Comment by coma64** [comment]
Sup this is because of the clipboard fix patch. Removing the the line `clipcopy(NULL)` at the end of `void setsel(char *str, Time t)` in `x.c`. Removing it should do the trick.

**Comment by Fogapod** [comment]
Thanks!
I wonder if it is intended behaviour or no, will it be fixed in this repo?

**Comment by coma64** [comment]
I'm pretty sure it's not intended, elsewise there wouldn't be a copy shortcut ;D

**Comment by mamg22** [comment]
This problem was caused by [this commit](https://github.com/LukeSmithxyz/st/commit/683341140065b3096ee9e7e3e3b042f9c52230a6), so just reverting it or deleting that line should fix it. It doesn't seem to be the intended behavior, because otherwise, why would `alt+c` exist if just selecting text copies it to the clipboard?

The normal behavior is that when you select text, `st` and most X programs place it in the primary X selection, and then the program can use some function to copy the contents of the primary selection over to the clipboard (what `alt+c` does).

That commit makes `st` copy the primary selection to the clipboard **every time** text is selected or the selection changes, thus just selecting the text already copies it to the clipboard.
