### ISSUE TITLE
New patches

### ISSUE THREAD

**Issue by plasmoduck** [LukeSmithxyz/st#205]
You should add the following patches for perfect box drawing and to avoid screen tearing glitches. A use case might be something like cava mpd visualizer.

https://st.suckless.org/patches/boxdraw/
https://st.suckless.org/patches/sync/

**Comment by LukeSmithxyz** [comment]
Open a working PR. People have tried to add boxdraw to this build, but I remember it not correctly functioning. I never bothered to figure it out.

**Comment by plasmoduck** [comment]
You have to enable it in config.h, 3 lines change 0 to 1. That's it. I manually patched it myself in my build. Just a bit of work.

**Comment by LukeSmithxyz** [comment]
If that's the case, if I have time soon I'll try adding it myself then.

What is sync for?

**Comment by plasmoduck** [comment]
Sync stops screen tearing. Not sure if you've used cava or ncmpcpp visualizations and seen tearing? Well the sync patch stops that.

**Comment by LukeSmithxyz** [comment]
Are we talking about the general screen tearing that occurs on Linux (at least xorg?). I mean that should be dealt with with system settings universally.

Or is this something specific to st? I've never seen something like this or heard complaints.

**Comment by avih** [comment]
> Are we talking about the general screen tearing that occurs on Linux (at least xorg?)

No. It's about the terminal tearing/flicker because it refreshes/redraws the screen before the application has completed the output - and then it has to redraw again once the remainder of the output from the application arrives. The autosync patch simply waits until no more content arrives - and then draws. See more details at the patch page (I'm the author).

**Comment by avih** [comment]
Also, I saw that at the boxdraw patch you enabled both `boxdraw_bold` and `boxdraw_braille`. IMHO these should be disabled by default.

Braille because while cute, it's a bit unexpected unless you want it that way.

Bold because other terminals seem to also disable bold for boxdraw lines (e.g. VTE). I think that fonts also don't always have bold, and because application which want thicker box lines usually explicitly use heavy lines (which boxdraw supports too regardless of bold). The only place I saw bold used with boxdraw lines was with htop in tree mode (F5), and it's bold just to get gray (bold black) and not for the thickness.

FWIW, Personally I have braille enabled and bold disabled, but that's just my personal taste.

**Comment by LukeSmithxyz** [comment]
Okay. Well I guess I'd sort of want to see examples of the differences between the variables.

As for sync, I mean I've never really seen this, or at least acknowledged it, so I don't know what it's fixing: is there any particular time when this occurs and is highly noticeable/a problem?

**Comment by avih** [comment]
Tearing and flicker are usually names for different aspects of the same thing. I'm sure you've seen flicker, e.g. at `less` or `vim` status line, or cursor flicker in tmux while the cursor is in one pane and there's some ongoing output at another pane, etc.

Tearing is usually more associated with unattended outputs like animation where the terminal draws partial image and then draws the remaining output. Examples of this would be any terminal audio visualizer (I tested with `cava` configured to 60fps, but it generally manifests in any fps), and also `mpv --really-quiet --vo=tct` or other applications which update the whole terminal area frequently.

**Comment by plasmoduck** [comment]
I'll try to record an example shortly to show. I'm in Australia so a bit of time difference. But it's 1pm here now. I'm just giving my son lunch then I'll try and make an example.

**Comment by plasmoduck** [comment]
I noticed you already got boxdraw working so thats fine. Here is an example, first video is your st without sync and the second is mine with sync applied. Notice the flicker/tear where there is an emply horizontal line across the bars now and then.
No sync: https://streamable.com/bafzbo
Sync: https://streamable.com/s785qc

**Comment by Mati20187** [comment]
I've noticed a lot of flickering in st so Sync would be very much appreciated. I have my own fork with boxdraw added but unfortunately there's no Sync for 0.8.2 so I'll have to move everything to 0.8.3 eventually. 
Could anybody test whether or not Sync fixes flicker in ncmpcpp's clock mode, tremc options or calcurse when scrolling with h or l? These are the programs in which I encountered the worst flickering and tearing

**Comment by avih** [comment]
> there's no Sync for 0.8.2

autosync ("Part 1") should work fine with 0.8.2, and generally it should be enough.

appsync ("Part 2") is more experimental and you probably don't really need it because there are barely any applications which make use of this feature, and indeed it doesn't apply cleanly to 0.8.2 (but if you know C then you should be able to resolve the conflict yourself).

**Comment by LukeSmithxyz** [comment]
Okay. I've added autosync.

**Comment by avih** [comment]
> Okay. I've added autosync.

FYI, autosync was merged upstream recently as-is.
