### ISSUE TITLE
Alt+O copies the command as well

### ISSUE THREAD

**Issue by strogiyotec** [LukeSmithxyz/st#217]
Hey Luke, here is the problem , the man page of st says
```
 Alt-o  Show dmenu menu of all recently run commands and copy the output of the chosen command to the clipboard.  xclip required.
```
But when I press Alt+O the dmenu appears and when I select a command and print it to the concole it print the command and then the output. Is it expected behavior? I personally don't want the command to be copied , only the output , thanks 
OS:
Ubuntu 18.04, st build, recent one from master xclip exists

**Comment by donihalim** [comment]
Got the same issue here on Artix with the latest build.

**Comment by FillePiano** [comment]
Changing the tail command on line 10 in the st-copyout file sort of solves the problem, not exactly as I want it but yeah... Luke probably knows his shell script... Ghgh Luke...

**Comment by LukeSmithxyz** [comment]
It's expected behavior. Edit the `st-copyout` file if you want otherwise. You can add: `| tail -n +2` between the last awk command and the xclip command to remove the first line. I'm sure you can also just edit that awk command to omit the first line, but I'm an awk brainlet most of the time so I can't tell you off the top of my head.
