### ISSUE TITLE
Font Spacing is Glitched for Me

### ISSUE THREAD

**Issue by disenthralling** [LukeSmithxyz/st#239]
OS: Manjaro Plasma 20.0.3 x86_64

So I've been having an issue with the fonts in this program since I installed it. When I start up st the font seems to always space itself out very widely. It's fixable by using `st -f 'font-name-here'`, but then it seems to clump the text together in a bizarre way. I've messed with the config.h file and recompiled it, and I reinstalled st several times but I haven't gotten it to work. I'm sure it is probably a simple fix, but I haven't found it yet. If you need to see some other files contents please let me know.

![Screenshot_20200724_104929](https://user-images.githubusercontent.com/68747474/88411208-260a7300-cd9d-11ea-9f42-3a678950f495.png)

**Comment by lucasemmoreira** [comment]
Hi there, I had the same issue with you after I upgraded manjaro. After some tries, I managed to find a fix although I am not sure if it is the best way.
Basically, I changed the font in the config.h
`static char *font = "freemono:size=14:antialias=true:autohint=true";
`
`
static char *font2[] = {"freemono:size=14:antialias=true"};
`
**Note:** for this font I downloaded the gnu free font from pacman

**Comment by Quist0n** [comment]
Are you using .Xresources or configuring it within your build files itself? I found that if you are configuring using .Xresources, you should specify the size not with:

`*.font: FONT-NAME:pixelsize=SIZE`

but with: 

`*.font: FONT-NAME:size=SIZE `

For me, just this day, when installing and working out the issue, if I used "pixelsize" it would blow up in my face and look similar to what I am seeing your screenshots. So try that instead. Perhaps it also works if you specify it in the config.h file. Something that also seemed to help is that in my .Xresources, I limited the font I chose down to 1. St would fail to launch because it could not read the font if I specified more than one. Good luck to you and I hope I was of help.

**Comment by LukeSmithxyz** [comment]
This nearly certainly is not relevant to this build. It just calls your default monofont, and it looks like Manjaro has some bad configuration that attempts to load a non-mono font instead, or at least one with weird settings. That's usually how it happens.
