### ISSUE TITLE
dmenu iso14755 patch issues.

### ISSUE THREAD

**Issue by mistersmee** [LukeSmithxyz/st#240]
On a fresh st build, or from the AUR, pressing Alt+Ctrl, i.e. activating the iso14755 patch, that allows you to input Unicode characters gives this error:

`X Error of failed request:  BadMatch (invalid parameter attributes)
 Major opcode of failed request:  62 (X_CopyArea)
 Serial number of failed request:  68
 Current serial number in output stream:  69`

and the newly-created dmenu instance crashes immediately.

I should note that I use i3, not dwm, so I do not know if this happens because of that.
I was able to reproduce this each time on my laptop. I do not know if it happens on other machines, as I have just the one laptop.

I was able to fix this by changing 

` #define ISO14755CMD             "dmenu -w \"$WINDOWID\" -p codepoint: </dev/null"`
in st.c
to 
` #define ISO14755CMD             "dmenu  -p codepoint: </dev/null"`

So, depending on whether this happens to others as well,  this should be changed in the source code too.
And if not, and it happens to just me, well, no problem, then. This issue will provide the fix to whoever encounters this problem later on.

**Comment by mutageneral** [comment]
This happens to me too. I also use i3.

I use Luke's build of st mostly stock with some keybinds modified.

All I have to do to trigger this bug is run `dmenu -w $(xdo id) < /dev/null`.
This is with stock dmenu. It works fine with stock st.

With Luke's dmenu, I can't seem to embed it in any windows at all, including stock st.
