### ISSUE TITLE
clipboard behavior

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/st#263]
hey luke, how do I restore previous behavior of the clipboard? The current one is a total mess for my workflow, and I'm unable to wrap my brain around it ... the annoyance I have is for example, I go to a website or a document, copy some text, and close the browser or document, and it's gone from the clipboard ... also the middle click and alt+c seem to use different clipboards ... I'd like to revert my fork of your st to its previous behavior before this change ... but I was unable to find which commit exactly does it

**Comment by olekhov** [comment]
I've set clipboard to PRIMARY. This is fine for my workflow. https://github.com/olekhov/st/commit/de362f0ccaf207fc1e70a3aec7756bc00046a7c3

**Comment by shahid777-py** [comment]
> also the middle click and alt+c seem to use different clipboards ... I'd like to revert my fork of your st to its previous behavior before this change ... but I

Ive been thinking about the same.

**Comment by LukeSmithxyz** [comment]
This has always been the default clipboard behavior of this terminal because it's the default clipboard behavior of Linux. Middle mouse pastes primary selection, not the clipboard and the xorg clipboard is not persistent when you close the relevant programs. That's the default functionality on Linux.

Install and run a clipboard manager if you want something different. That's what they do. It's not the job of a terminal emulator to jury-rig a different system.

**Comment by kronikpillow** [comment]
Im pretty sure it wasn't when i started using larbs, alt c and mouse selection were using the same clipboard, and when i copied something it didn't go awol after closing the source, but ok, ill figure it out

**Comment by StingJohnson** [comment]
> Im pretty sure it wasn't when i started using larbs, alt c and mouse selection were using the same clipboard, and when i copied something it didn't go awol after closing the source, but ok, ill figure it out

did you find out the reason please?
