### ISSUE TITLE
Text gets truncated instead of resized

### ISSUE THREAD

**Issue by mrpewpew** [LukeSmithxyz/st#28]
Hello, I use st with i3wm and when a new window spawn next to a window containing a terminal, the text on that terminal gets truncated instead of resizing. I never noticed a similar issue in your setup while watching your videos. Is there a specific patch for this problem ?

**Comment by mrpewpew** [comment]
Ah I see. However, there is a scrollback patch. Doesn't it have to store output for us to scroll back too ? I am not good enough with C to investigate how it does that, though. I will try the tmux way but I need to figure a good way to handle nested tmux since I connect to remote machines with tmux on them

**Comment by LukeSmithxyz** [comment]
It would actually be a lot more complicated than mere scrollback, because you would have to keep track of line breaks and basically reoutput everything. E.g. let's say you run `pacman -Sy` and there appear loading bars... well, what happens to the loading bars when you resize? They'd have to be recreated and resized with information from the original program, etc.

**Comment by Eksapsy** [comment]
If anyone's interested at that point, since ST is not gonna offer such functionality until someone makes a big patch about it, personally I just launch a TMUX session

Put this in your `~/.bashrc` or `~/.zshrc`
```bash
if [ -z "$TMUX" ]
then
    tmux attach -t TMUX || tmux new -s TMUX
fi
```

Just learn to use windows in your tmux session, since that script is not gonna start a new session in every new shell instance you open.

Also, do not use this script to avoid that
```bash
exec tmux
//or
tmux
```
since that is gonna bloat your tmux with a new session every time you open a new shell, which session is never exited even after you exited the shell.

**Comment by mrpewpew** [comment]
@Eksapsy Yep that's what I ended up doing. It works fine

**Comment by reverseila** [comment]
Here is a fix for that: https://groups.google.com/g/wmii/c/iJvvk0oIlIk?pli=1

Simply install [scroll](https://tools.suckless.org/scroll/) program (`clone ...; cd scroll; make; sudo make clean install`) and afterwards spawn terminals with the command: `st -e scroll /bin/<fav shell>`

For example, I have the following termcmd (command to spawn a terminal) in my dwm config:
```c
 static const char *termcmd[] = { "st", "-e", "scroll", "/bin/zsh", NULL };
```
also for scratchpad, if you have one:
```c
const char *spcmd[]    = {"st", "-n", "spterm", "-g", "90x23", "-e", "scroll", "/bin/zsh", NULL };
```
---
From the scroll webpage:

> At the moment it is in an experimental state. Its not recommended for productive use.

Sometimes (1 out of 10 maybe) when I spawn new terminal an `%` appears persistently at the end of output of every command. I managed to get rid of with opening and closing `lf` file manager. Not sure if it's a shell problem or related to scroll. Anyhow, that is my only problem with it.

**Comment by LukeSmithxyz** [comment]
Scroll used to be in this build, but I removed it because it's awful and regularly breaks everything.

**Comment by reverseila** [comment]
This patch does not truncate text on resize. It works fine without any problem, so far for me. The problem with this is that it does not wrap content on resize. It is called column patch according to this [guy](https://github.com/siduck76/st).

https://github.com/nimaipatel/st/blob/master/patches/7672445bab01cb4e861651dc540566ac22e25812.diff
