### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/st#284]
scroll really sucks and is fragile makes the terminal nearly usable.

I might remove it and restore the old scrollback patch until scroll is more bugfree.

**Comment by narukeh** [comment]
i hate it too. still using your old 0.8.2 cause of this.
at least with the scrollback patch, text staid fine if you did a horizontal split, while with `scroll` gets drunk anyhow that you split, and then poorly assembles the text.
it also changes the colors a tiny bit, though the colorscheme was not touched in the config.h
while i dont really like going back (bc i like vertical split (super+t)), i just wished `scroll` worked how its supposed to.

**Comment by JC-Morph** [comment]
Thirded. I'm also getting the issue @BachoSeven mentioned in #274, "some terminals with neovim open in them "freeze"".
Only happens after resizing/opening additional terminal windows. Only fix is to super+q them, then deal with the swap file. Updated just yesterday since I couldn't be arsed to deal with the color changes and it's already doing my nut. Rolling back again for now.

**Comment by LukeSmithxyz** [comment]
Old scrollback patch is restored. If anyone keeps track of the scroll program, let me know if it gets good.
