### ISSUE TITLE
Not obeying Xresources, weird font + transparency

### ISSUE THREAD

**Issue by ThatOneCalculator** [LukeSmithxyz/st#307]
It looks like this, nothing like my Xresources.
![image](https://user-images.githubusercontent.com/44733677/124694841-e4cc7f80-de96-11eb-8e5b-13f21350fa9a.png)
~/.Xresources
```
Xcursor.theme: Quintom_Ink
Xcursor.size: 25
*.font:	cherry:pixelsize=12:antialias=false:autohint=false;
*.alpha: 1.0
```

**Comment by horodnicdragos** [comment]
Hi @ThatOneCalculator!

I've had issues with truecolor myself starting from this commit:
https://github.com/LukeSmithxyz/st/commit/fa3c401390e1477ff4aae6b91fcf18eded478814

What happens if you checkout to the commit before and recompile? (73c034ba05101e2fc337183af1cdec5bfe318b99) Does that solve your problem?
