### ISSUE TITLE
Wanted: Libsixel Support

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/st#36]
I'd like to either patch in libsixel support natively, or add an option patch for it so my build of `st` would be able to use sixel to view images and moving gifs.

There is an already existing patch for an earlier version of st here: https://gist.github.com/saitoha/70e0fdf22e3e8f63ce937c7f7da71809

I haven't bothered to get this working because it requires more than just dealling with `.rej` files, but also I think some variables and functions have been renamed and moved between files. So I haven't actually gotten this working on my current updated build.

So I'm curious if anyone else with some time to tinker is willing to play around with this.

Of course, that one linked is a *big* patch (putting the source over 5k lines), hence why I might prefer it as a patchable diff. Of course, if you're more familiar with sixel, you might be able to do it more elegantly.

**Comment by LukeSmithxyz** [comment]
For those unfamiliar, as I alluded to above, this would ideally be adding very robust image and moving gif previews. Image previews in st are okay, but disappear on mouse-away and obviously can't display gifs.

Now for ranger image previews in st, to be clear, I think that sixel compatibility would have to be added to ranger as well, so adding this patch to st would as of now only allow the different image previews outside of ranger. Still, one has to come before the other.

**Comment by mayjs** [comment]
I've just applied the patch and worked around all the incompatible bits so st compiles again in [my fork](https://github.com/mayjs/st), but it crashes as soon as sixel graphics occur for me. I'm testing with the `lsix` utility, and get this output:
```
erresc: unknown str ESC]11
erresc: unknown csi ESC[14t
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  72 (X_PutImage)
  Serial number of failed request:  1818
  Current serial number in output stream:  1832
```

I can't really make much sense of this because I don't know anything about sixels, but my guess is that something goes wrong when parsing the sixels (hence the unknown str and csi outputs) and as a result of that, invalid arguments are passed to `X_PutImage`. If I have time, I'll try to figure it out using gdb.

**Comment by mayjs** [comment]
Actually, I just found [](https://github.com/charlesdaniels/st) and tested it, this seems to fix the issues I had and is based on the same gist. Hopefully this is compatible with all of the other patches in this fork so it can be easily integrated.
