### ISSUE TITLE
Trying to patch xresources

### ISSUE THREAD

**Issue by ReekyMarko** [LukeSmithxyz/st#44]
Hi! Sorry if this is not the right place but I got inspired to do an st build by your youtube videos so this was the first place I thought to come and seek help. I'm not using your build, but just a vanilla st with a couple of patches added. I'm doing this so I can actually learn how to configure this thing. Sorry in advance, I'm a total noob with suckless tools as I started only today.

So everything in my build went fine until I started to apply the xresources patch. I think the problem might be that the patch is not specifically for my version of st, the patch just has a date on it. Also I'm building with makepkg instead of normal make. Here is my PKGBUILD:

```
pkgname=reeky-st
appname='st'
conflicts=(${appname})
provides=(${appname})
pkgver=0.8
pkgrel=0
pkgdesc='A simple virtual terminal emulator for X. My personal config.'
arch=('i686' 'x86_64')
license=('MIT')
depends=('libxext' 'libxft')
makedepends=('ncurses')
url="http://st.suckless.org"

_patches=(
	"https://st.suckless.org/patches/scrollback/$appname-scrollback-$pkgver.diff"
	"https://st.suckless.org/patches/scrollback/$appname-scrollback-mouse-$pkgver.diff"
	"https://st.suckless.org/patches/scrollback/$appname-scrollback-mouse-altscreen-$pkgver.diff"
	"https://st.suckless.org/patches/xresources/st-xresources-20190105-9f80f67.diff"
)

source=(
	"http://dl.suckless.org/st/$appname-$pkgver.tar.gz"
	"config.h"
	"st.desktop"
	"${_patches[@]}"
)

md5sums=('4cae10d2dcc1f97ead37181b21b54212'
         'e89bc7a7aa2beb6bc7a43597e2f562cc'
         'a984de398f12717f0144b9a2bd2953ed'
         'bbe056eaed5914f55ccea001ca7f05e9'
         '72227737f6cd831afd014a3613bd559d'
         'fa0bf6c0dae5a69e3b1916ce093f6aff'
         '11e28f38988de5141bfdf0da8cbfde8a')

prepare() {
	cd $srcdir/$appname-$pkgver
	
	for patch in "${_patches[@]}"; do
		echo "Applying patch $(basename $patch)..."
		patch -Np1 -i "$srcdir/$(basename $patch)"
	done
	
	# skip terminfo which conflicts with nsurses
	sed -i '/tic /d' Makefile
	
	cp $srcdir/config.h config.h
}

build() {
	cd $srcdir/$appname-$pkgver
	make X11INC=/usr/include/X11 X11LIB=/usr/lib/X11
}

package() {
	cd $srcdir/$appname-$pkgver
	make PREFIX=/usr DESTDIR="$pkgdir" TERMINFO="$pkgdir/usr/share/terminfo" install
	
	install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$appname/LICENSE"
	install -Dm644 README "$pkgdir/usr/share/doc/$appname/README"
	
	mkdir "$pkgdir/usr/share/applications"
	install -m755 "$srcdir/st.desktop" "$pkgdir/usr/share/applications/st.desktop"
}
```
And here is the error it spurts out:
```
patching file x.c
Hunk #3 succeeded at 802 (offset 5 lines).
Hunk #4 FAILED at 1019.
Hunk #5 succeeded at 1888 (offset 4 lines).
Hunk #6 succeeded at 2014 with fuzz 1 (offset 4 lines).
1 out of 6 hunks FAILED -- saving rejects to file x.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
```

Any idea why this is happening?

EDIT: Here is also the x.c.j rej:
```
--- x.c
+++ x.c
@@ -1019,8 +1033,6 @@ xinit(int cols, int rows)
 	pid_t thispid = getpid();
 	XColor xmousefg, xmousebg;
 
-	if (!(xw.dpy = XOpenDisplay(NULL)))
-		die("can't open display\n");
 	xw.scr = XDefaultScreen(xw.dpy);
 	xw.vis = XDefaultVisual(xw.dpy, xw.scr);
```

**Comment by LukeSmithxyz** [comment]
This is just a basic patch incompatibility. Read the manual on patching and diffing. Remember that these patches are just text files that look for a general pattern a file and add/change/delete lines as in the patch. If you chain multiple patches, well, eventually you're going to change the input to one of the later patches, so it won't work.

Arch Linux package builds and suckless patches don't mix. suckless patches are all targeted to the default build of the program. Actually, most all patches are, and I think it's sort of a bad idea to actually use the pkgbuild patch functionality. I'd rather build a build that looks to a git url of an already patched build that you make.

Anyway, as to how to solve your immediate problem. Do it (all the patching) manually. Then open your patch and `.rej` and find what changes should be done. So the `.rej` file you post shows that those two lines were supposed to be deleted by the patch. Find either them or what another patch turned them into and remove them. Upload your git repo somewhere where your pkgbuild can dl it and use that instead of the upstream with all those automatic patches.

**Comment by ReekyMarko** [comment]
Thanks for your input! I would rather stick with a PKGBUILD, since it's much more portable. I will look into creating my own patches, which I can probaly source from a Github gist or something.
