### ISSUE TITLE
Opacity issue 2.0

### ISSUE THREAD

**Issue by TpouHuK** [LukeSmithxyz/st#49]
If `st` launched with `-n` argument then opacity from Xresourses ignored:

`st -n asdf`

**Comment by LukeSmithxyz** [comment]
I suppose you have `st.alpha: 240` rather than `*.alpha: 240` in your file then.

`st` instances of different names will read different Xresources values. This allows you to set separate fonts/cursors/sizes/alpha values for each.

Let's say you want a kind of st instance labeled asdf run as `st -n asdf`. You could set a specific font by saying `asdf.font: Monospace-24;`, etc. Again, if you want this to be constant, use `*`.
