### ISSUE TITLE
st-copyout does not work well with powerline prompts

### ISSUE THREAD

**Issue by rusmelezi** [LukeSmithxyz/st#86]
I tested it with fish and zsh, several prompts and themes like agnoster, powerlevel10k(doesn't work with both) but prompts without powerline fonts it works well.

**Comment by LukeSmithxyz** [comment]
The only thing that matters is that the leftmost element. Not the shell or anything else. It works for zsh for me---the issue is just is the prompt distinct enough and constant.

An example, in my system, the leftmost independent non-whitespace word is: `[luke@core` which the script will find and locate and there will nearly certainly be no false positives unless that exact sequence is in the output at the very beginning of a line.

But say I had a prompt with the exact time on the left, so `[15:41:33` then some more stuff. In that case, the script wouldn't be able to find any similar lines so it wouldn't work. Same is true if you have your directory on the left and then `cd` somewhere else.

If you have simple PRs to make this script a little better, I'm open to them, but I'll go ahead and say that in order for this little function to work on every possible prompt is basically impossible as is (or at least too much work for me). As it is, it works with most simple prompts and should be shell-independent.

Of course some brighter idea for finding the prompt might come to someone.

**Comment by codeitlikemiley** [comment]
you need to patch st , it has a patch for powerline fonts. the patch name is font2.
i just did patch it now to my new laptop
