### ISSUE TITLE
Magnet link to clipboard

### ISSUE THREAD

**Issue by josecleiton** [LukeSmithxyz/st#87]
I'm trying to add magnet links to the chad pipe in config.h but doesn't work when i press the bind, but when i call it in st (directly) works. Please, help me, i'm newbie in regex. 
I'm using zsh.
`sed 's/.*│//g' | tr -d '\n' | grep -aEo '(((http|https)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./&%?=_-]*)|((magnet:\?xt=urn:btih:)[a-zA-Z0-9]*)' | uniq | dmenu -p 'Follow which url?' -l 10 | xargs -r xdg-open'`

**Comment by LukeSmithxyz** [comment]
Put another `\` before the `?` and see if that works.

**Comment by josecleiton** [comment]
Oh shit, worked. Thanks! Luke let me ask you two more things: 1) why pipe this `sed 's/^www./http:\\/\\/www\\./g' ` after the `grep` command? 2) when I use the mouse scroll in st a bunch of words show up in cursor. Why?

**Comment by LukeSmithxyz** [comment]
Glad it works. I might add this to my own build since it might be nice to have.

On your first question, `xdg-open` will not recognize a string of characters like `www.lukesmith.xyz` as a website, so that sed command adds `http://` to the beginning of such lines so it will.

I'm not sure what you mean by your second question. Feel free to clarify.

**Comment by josecleiton** [comment]
The second question was a bug with a crap oh-my-zsh plugin indeed, nevermind. Fixed.

**Comment by josecleiton** [comment]
Another question, there's a book or something about regular expression and posix shell? After you video about bash vs sh i've realized that i dont know shell script, but bash.
